language: c

addons:
  apt_packages:
    - build-essential
    - libc6:i386
    - libgcc1:i386
    - gcc-4.6-base:i386
    - libstdc++5:i386
    - libstdc++6:i386
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1

install:
  - wget https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-linux.tar.bz2
  - tar xfj gcc-arm-none-eabi-5_2-2015q4-20151219-linux.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_2-2015q4/bin/

script: make PREFIX=arm-none-eabi-

